services:

  postgres:
    image: postgres:latest
    container_name: uao-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  uao-app:
    container_name: uao-app
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
