# Generated by Django 5.2.1 on 2025-06-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario está activo.')),
                ('is_staff', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('administrativo', 'Administrativo'), ('auxiliar_administrativo', 'Auxiliar Administrativo'), ('alumno', 'Alumno'), ('cajero', 'Cajero'), ('escolar', 'Escolar')], default='alumno', max_length=30)),
                ('desde', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del usuario.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
