# Generated by Django 5.2.1 on 2025-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('administrador', 'Administrador'), ('superadmin', 'Super Administrador'), ('usuario', 'Usuario')], default='alumno', max_length=20),
        ),
    ]
