# Generated by Django 5.2.1 on 2025-06-15 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0003_alter_carrera_fecha_actualizacion_and_more'),
        ('direcciones', '0001_initial'),
        ('extensiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('periodo_ingreso', models.SmallIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('semestre', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='carreras.carrera')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='direcciones.direccion')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='extensiones.extension')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido_paterno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bachiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_egreso', models.DateField()),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('tipo_bachillerato', models.CharField(max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachiller', to='alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_nacimiento', models.BooleanField(default=False)),
                ('curp', models.BooleanField(default=False)),
                ('certificado_bachillerato', models.BooleanField(default=False)),
                ('certificado_medico', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['alumno'],
            },
        ),
    ]
