# Generated by Django 5.2.1 on 2025-06-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachiller',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bachiller', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='alumnos.alumno'),
        ),
    ]
