# Generated by Django 5.2.1 on 2025-06-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_bachiller_alumno_alter_documentacion_alumno'),
        ('direcciones', '0001_initial'),
        ('extensiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='direcciones.direccion'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='extension',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='extensiones.extension'),
        ),
    ]
