# Generated by Django 5.2.1 on 2025-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_direccion_alter_alumno_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10),
        ),
    ]
