# Generated by Django 5.2.1 on 2025-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='abreviatura',
            field=models.CharField(default='', help_text="Abreviatura de la carrera, por ejemplo: 'II'.", max_length=10, unique=True),
        ),
    ]
