# Generated by Django 5.2.1 on 2025-06-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
        ('extensiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='Licenciatura', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CarreraExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_extension', to='carreras.carrera')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_extension', to='extensiones.extension')),
            ],
            options={
                'verbose_name': 'Carrera por Extensión',
                'verbose_name_plural': 'Carreras por Extensión',
                'unique_together': {('carrera', 'extension')},
            },
        ),
    ]
