# Generated by Django 5.2.1 on 2025-06-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_carrera_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='Licenciatura', max_length=30),
        ),
    ]
