# Generated by Django 5.2.1 on 2025-06-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_carrera_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='abreviatura',
            field=models.CharField(blank=True, default='', help_text="Abreviatura de la carrera, por ejemplo: 'II'.", max_length=10, unique=True),
        ),
    ]
