# Generated by Django 5.2.1 on 2025-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='contacto',
            field=models.CharField(max_length=20, verbose_name='Numero de Contacto'),
        ),
    ]
